// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/auth/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDummyLoginUsecase creates a new instance of MockDummyLoginUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDummyLoginUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDummyLoginUsecase {
	mock := &MockDummyLoginUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDummyLoginUsecase is an autogenerated mock type for the DummyLoginUsecase type
type MockDummyLoginUsecase struct {
	mock.Mock
}

type MockDummyLoginUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDummyLoginUsecase) EXPECT() *MockDummyLoginUsecase_Expecter {
	return &MockDummyLoginUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockDummyLoginUsecase
func (_mock *MockDummyLoginUsecase) Execute(ctx context.Context, role string) (dto.TokenResponse, error) {
	ret := _mock.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (dto.TokenResponse, error)); ok {
		return returnFunc(ctx, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) dto.TokenResponse); ok {
		r0 = returnFunc(ctx, role)
	} else {
		r0 = ret.Get(0).(dto.TokenResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDummyLoginUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDummyLoginUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
func (_e *MockDummyLoginUsecase_Expecter) Execute(ctx interface{}, role interface{}) *MockDummyLoginUsecase_Execute_Call {
	return &MockDummyLoginUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, role)}
}

func (_c *MockDummyLoginUsecase_Execute_Call) Run(run func(ctx context.Context, role string)) *MockDummyLoginUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDummyLoginUsecase_Execute_Call) Return(tokenResponse dto.TokenResponse, err error) *MockDummyLoginUsecase_Execute_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *MockDummyLoginUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, role string) (dto.TokenResponse, error)) *MockDummyLoginUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
