// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/rooms"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoomStorage creates a new instance of MockRoomStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomStorage {
	mock := &MockRoomStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoomStorage is an autogenerated mock type for the RoomStorage type
type MockRoomStorage struct {
	mock.Mock
}

type MockRoomStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomStorage) EXPECT() *MockRoomStorage_Expecter {
	return &MockRoomStorage_Expecter{mock: &_m.Mock}
}

// CreateRoom provides a mock function for the type MockRoomStorage
func (_mock *MockRoomStorage) CreateRoom(ctx context.Context, name string, description string, capacity int) (string, error) {
	ret := _mock.Called(ctx, name, description, capacity)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) (string, error)); ok {
		return returnFunc(ctx, name, description, capacity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) string); ok {
		r0 = returnFunc(ctx, name, description, capacity)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = returnFunc(ctx, name, description, capacity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomStorage_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type MockRoomStorage_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description string
//   - capacity int
func (_e *MockRoomStorage_Expecter) CreateRoom(ctx interface{}, name interface{}, description interface{}, capacity interface{}) *MockRoomStorage_CreateRoom_Call {
	return &MockRoomStorage_CreateRoom_Call{Call: _e.mock.On("CreateRoom", ctx, name, description, capacity)}
}

func (_c *MockRoomStorage_CreateRoom_Call) Run(run func(ctx context.Context, name string, description string, capacity int)) *MockRoomStorage_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRoomStorage_CreateRoom_Call) Return(s string, err error) *MockRoomStorage_CreateRoom_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRoomStorage_CreateRoom_Call) RunAndReturn(run func(ctx context.Context, name string, description string, capacity int) (string, error)) *MockRoomStorage_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomByID provides a mock function for the type MockRoomStorage
func (_mock *MockRoomStorage) GetRoomByID(ctx context.Context, id string) (*rooms.Room, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomByID")
	}

	var r0 *rooms.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*rooms.Room, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *rooms.Room); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rooms.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomStorage_GetRoomByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomByID'
type MockRoomStorage_GetRoomByID_Call struct {
	*mock.Call
}

// GetRoomByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoomStorage_Expecter) GetRoomByID(ctx interface{}, id interface{}) *MockRoomStorage_GetRoomByID_Call {
	return &MockRoomStorage_GetRoomByID_Call{Call: _e.mock.On("GetRoomByID", ctx, id)}
}

func (_c *MockRoomStorage_GetRoomByID_Call) Run(run func(ctx context.Context, id string)) *MockRoomStorage_GetRoomByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomStorage_GetRoomByID_Call) Return(room *rooms.Room, err error) *MockRoomStorage_GetRoomByID_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockRoomStorage_GetRoomByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*rooms.Room, error)) *MockRoomStorage_GetRoomByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRooms provides a mock function for the type MockRoomStorage
func (_mock *MockRoomStorage) GetRooms(ctx context.Context) ([]*rooms.Room, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRooms")
	}

	var r0 []*rooms.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*rooms.Room, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*rooms.Room); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*rooms.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomStorage_GetRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRooms'
type MockRoomStorage_GetRooms_Call struct {
	*mock.Call
}

// GetRooms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomStorage_Expecter) GetRooms(ctx interface{}) *MockRoomStorage_GetRooms_Call {
	return &MockRoomStorage_GetRooms_Call{Call: _e.mock.On("GetRooms", ctx)}
}

func (_c *MockRoomStorage_GetRooms_Call) Run(run func(ctx context.Context)) *MockRoomStorage_GetRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomStorage_GetRooms_Call) Return(rooms1 []*rooms.Room, err error) *MockRoomStorage_GetRooms_Call {
	_c.Call.Return(rooms1, err)
	return _c
}

func (_c *MockRoomStorage_GetRooms_Call) RunAndReturn(run func(ctx context.Context) ([]*rooms.Room, error)) *MockRoomStorage_GetRooms_Call {
	_c.Call.Return(run)
	return _c
}
