// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/slots"
	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/slots/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetSlotsUsecase creates a new instance of MockGetSlotsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetSlotsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetSlotsUsecase {
	mock := &MockGetSlotsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetSlotsUsecase is an autogenerated mock type for the GetSlotsUsecase type
type MockGetSlotsUsecase struct {
	mock.Mock
}

type MockGetSlotsUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetSlotsUsecase) EXPECT() *MockGetSlotsUsecase_Expecter {
	return &MockGetSlotsUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockGetSlotsUsecase
func (_mock *MockGetSlotsUsecase) Execute(ctx context.Context, input dto.GetSlotsInput) ([]*slots.Slot, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*slots.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetSlotsInput) ([]*slots.Slot, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetSlotsInput) []*slots.Slot); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*slots.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GetSlotsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetSlotsUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetSlotsUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.GetSlotsInput
func (_e *MockGetSlotsUsecase_Expecter) Execute(ctx interface{}, input interface{}) *MockGetSlotsUsecase_Execute_Call {
	return &MockGetSlotsUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockGetSlotsUsecase_Execute_Call) Run(run func(ctx context.Context, input dto.GetSlotsInput)) *MockGetSlotsUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.GetSlotsInput
		if args[1] != nil {
			arg1 = args[1].(dto.GetSlotsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetSlotsUsecase_Execute_Call) Return(slots1 []*slots.Slot, err error) *MockGetSlotsUsecase_Execute_Call {
	_c.Call.Return(slots1, err)
	return _c
}

func (_c *MockGetSlotsUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, input dto.GetSlotsInput) ([]*slots.Slot, error)) *MockGetSlotsUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
