// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/bookings/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetMyBookingsUsecase creates a new instance of MockGetMyBookingsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetMyBookingsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetMyBookingsUsecase {
	mock := &MockGetMyBookingsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetMyBookingsUsecase is an autogenerated mock type for the GetMyBookingsUsecase type
type MockGetMyBookingsUsecase struct {
	mock.Mock
}

type MockGetMyBookingsUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetMyBookingsUsecase) EXPECT() *MockGetMyBookingsUsecase_Expecter {
	return &MockGetMyBookingsUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockGetMyBookingsUsecase
func (_mock *MockGetMyBookingsUsecase) Execute(ctx context.Context, input dto.GetMyBookingsInput) (*dto.GetMyBookingsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *dto.GetMyBookingsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetMyBookingsInput) (*dto.GetMyBookingsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetMyBookingsInput) *dto.GetMyBookingsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetMyBookingsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GetMyBookingsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetMyBookingsUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetMyBookingsUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.GetMyBookingsInput
func (_e *MockGetMyBookingsUsecase_Expecter) Execute(ctx interface{}, input interface{}) *MockGetMyBookingsUsecase_Execute_Call {
	return &MockGetMyBookingsUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockGetMyBookingsUsecase_Execute_Call) Run(run func(ctx context.Context, input dto.GetMyBookingsInput)) *MockGetMyBookingsUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.GetMyBookingsInput
		if args[1] != nil {
			arg1 = args[1].(dto.GetMyBookingsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetMyBookingsUsecase_Execute_Call) Return(getMyBookingsOutput *dto.GetMyBookingsOutput, err error) *MockGetMyBookingsUsecase_Execute_Call {
	_c.Call.Return(getMyBookingsOutput, err)
	return _c
}

func (_c *MockGetMyBookingsUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, input dto.GetMyBookingsInput) (*dto.GetMyBookingsOutput, error)) *MockGetMyBookingsUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
