// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/rooms"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetRoomsUsecase creates a new instance of MockGetRoomsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetRoomsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetRoomsUsecase {
	mock := &MockGetRoomsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetRoomsUsecase is an autogenerated mock type for the GetRoomsUsecase type
type MockGetRoomsUsecase struct {
	mock.Mock
}

type MockGetRoomsUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetRoomsUsecase) EXPECT() *MockGetRoomsUsecase_Expecter {
	return &MockGetRoomsUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockGetRoomsUsecase
func (_mock *MockGetRoomsUsecase) Execute(ctx context.Context) ([]*rooms.Room, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*rooms.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*rooms.Room, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*rooms.Room); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*rooms.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetRoomsUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetRoomsUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGetRoomsUsecase_Expecter) Execute(ctx interface{}) *MockGetRoomsUsecase_Execute_Call {
	return &MockGetRoomsUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockGetRoomsUsecase_Execute_Call) Run(run func(ctx context.Context)) *MockGetRoomsUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGetRoomsUsecase_Execute_Call) Return(rooms1 []*rooms.Room, err error) *MockGetRoomsUsecase_Execute_Call {
	_c.Call.Return(rooms1, err)
	return _c
}

func (_c *MockGetRoomsUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context) ([]*rooms.Room, error)) *MockGetRoomsUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
