// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/bookings/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetAllBookingsUsecase creates a new instance of MockGetAllBookingsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetAllBookingsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetAllBookingsUsecase {
	mock := &MockGetAllBookingsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetAllBookingsUsecase is an autogenerated mock type for the GetAllBookingsUsecase type
type MockGetAllBookingsUsecase struct {
	mock.Mock
}

type MockGetAllBookingsUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetAllBookingsUsecase) EXPECT() *MockGetAllBookingsUsecase_Expecter {
	return &MockGetAllBookingsUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockGetAllBookingsUsecase
func (_mock *MockGetAllBookingsUsecase) Execute(ctx context.Context, input dto.GetAllBookingsInput) (*dto.GetAllBookingsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *dto.GetAllBookingsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetAllBookingsInput) (*dto.GetAllBookingsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetAllBookingsInput) *dto.GetAllBookingsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetAllBookingsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GetAllBookingsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetAllBookingsUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetAllBookingsUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.GetAllBookingsInput
func (_e *MockGetAllBookingsUsecase_Expecter) Execute(ctx interface{}, input interface{}) *MockGetAllBookingsUsecase_Execute_Call {
	return &MockGetAllBookingsUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockGetAllBookingsUsecase_Execute_Call) Run(run func(ctx context.Context, input dto.GetAllBookingsInput)) *MockGetAllBookingsUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.GetAllBookingsInput
		if args[1] != nil {
			arg1 = args[1].(dto.GetAllBookingsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetAllBookingsUsecase_Execute_Call) Return(getAllBookingsOutput *dto.GetAllBookingsOutput, err error) *MockGetAllBookingsUsecase_Execute_Call {
	_c.Call.Return(getAllBookingsOutput, err)
	return _c
}

func (_c *MockGetAllBookingsUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, input dto.GetAllBookingsInput) (*dto.GetAllBookingsOutput, error)) *MockGetAllBookingsUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
