// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/schedules"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScheduleStorage creates a new instance of MockScheduleStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleStorage {
	mock := &MockScheduleStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduleStorage is an autogenerated mock type for the ScheduleStorage type
type MockScheduleStorage struct {
	mock.Mock
}

type MockScheduleStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleStorage) EXPECT() *MockScheduleStorage_Expecter {
	return &MockScheduleStorage_Expecter{mock: &_m.Mock}
}

// CreateSchedule provides a mock function for the type MockScheduleStorage
func (_mock *MockScheduleStorage) CreateSchedule(ctx context.Context, roomID string, startTime time.Time, endTime time.Time, days []int) (*schedules.Schedule, error) {
	ret := _mock.Called(ctx, roomID, startTime, endTime, days)

	if len(ret) == 0 {
		panic("no return value specified for CreateSchedule")
	}

	var r0 *schedules.Schedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, []int) (*schedules.Schedule, error)); ok {
		return returnFunc(ctx, roomID, startTime, endTime, days)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, []int) *schedules.Schedule); ok {
		r0 = returnFunc(ctx, roomID, startTime, endTime, days)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schedules.Schedule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, []int) error); ok {
		r1 = returnFunc(ctx, roomID, startTime, endTime, days)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduleStorage_CreateSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSchedule'
type MockScheduleStorage_CreateSchedule_Call struct {
	*mock.Call
}

// CreateSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - startTime time.Time
//   - endTime time.Time
//   - days []int
func (_e *MockScheduleStorage_Expecter) CreateSchedule(ctx interface{}, roomID interface{}, startTime interface{}, endTime interface{}, days interface{}) *MockScheduleStorage_CreateSchedule_Call {
	return &MockScheduleStorage_CreateSchedule_Call{Call: _e.mock.On("CreateSchedule", ctx, roomID, startTime, endTime, days)}
}

func (_c *MockScheduleStorage_CreateSchedule_Call) Run(run func(ctx context.Context, roomID string, startTime time.Time, endTime time.Time, days []int)) *MockScheduleStorage_CreateSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 []int
		if args[4] != nil {
			arg4 = args[4].([]int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockScheduleStorage_CreateSchedule_Call) Return(schedule *schedules.Schedule, err error) *MockScheduleStorage_CreateSchedule_Call {
	_c.Call.Return(schedule, err)
	return _c
}

func (_c *MockScheduleStorage_CreateSchedule_Call) RunAndReturn(run func(ctx context.Context, roomID string, startTime time.Time, endTime time.Time, days []int) (*schedules.Schedule, error)) *MockScheduleStorage_CreateSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// GetScheduleByID provides a mock function for the type MockScheduleStorage
func (_mock *MockScheduleStorage) GetScheduleByID(ctx context.Context, scheduleID string) (*schedules.Schedule, error) {
	ret := _mock.Called(ctx, scheduleID)

	if len(ret) == 0 {
		panic("no return value specified for GetScheduleByID")
	}

	var r0 *schedules.Schedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*schedules.Schedule, error)); ok {
		return returnFunc(ctx, scheduleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *schedules.Schedule); ok {
		r0 = returnFunc(ctx, scheduleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schedules.Schedule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, scheduleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduleStorage_GetScheduleByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScheduleByID'
type MockScheduleStorage_GetScheduleByID_Call struct {
	*mock.Call
}

// GetScheduleByID is a helper method to define mock.On call
//   - ctx context.Context
//   - scheduleID string
func (_e *MockScheduleStorage_Expecter) GetScheduleByID(ctx interface{}, scheduleID interface{}) *MockScheduleStorage_GetScheduleByID_Call {
	return &MockScheduleStorage_GetScheduleByID_Call{Call: _e.mock.On("GetScheduleByID", ctx, scheduleID)}
}

func (_c *MockScheduleStorage_GetScheduleByID_Call) Run(run func(ctx context.Context, scheduleID string)) *MockScheduleStorage_GetScheduleByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScheduleStorage_GetScheduleByID_Call) Return(schedule *schedules.Schedule, err error) *MockScheduleStorage_GetScheduleByID_Call {
	_c.Call.Return(schedule, err)
	return _c
}

func (_c *MockScheduleStorage_GetScheduleByID_Call) RunAndReturn(run func(ctx context.Context, scheduleID string) (*schedules.Schedule, error)) *MockScheduleStorage_GetScheduleByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetScheduleByRoomID provides a mock function for the type MockScheduleStorage
func (_mock *MockScheduleStorage) GetScheduleByRoomID(ctx context.Context, roomID string) (*schedules.Schedule, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetScheduleByRoomID")
	}

	var r0 *schedules.Schedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*schedules.Schedule, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *schedules.Schedule); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schedules.Schedule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduleStorage_GetScheduleByRoomID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScheduleByRoomID'
type MockScheduleStorage_GetScheduleByRoomID_Call struct {
	*mock.Call
}

// GetScheduleByRoomID is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockScheduleStorage_Expecter) GetScheduleByRoomID(ctx interface{}, roomID interface{}) *MockScheduleStorage_GetScheduleByRoomID_Call {
	return &MockScheduleStorage_GetScheduleByRoomID_Call{Call: _e.mock.On("GetScheduleByRoomID", ctx, roomID)}
}

func (_c *MockScheduleStorage_GetScheduleByRoomID_Call) Run(run func(ctx context.Context, roomID string)) *MockScheduleStorage_GetScheduleByRoomID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScheduleStorage_GetScheduleByRoomID_Call) Return(schedule *schedules.Schedule, err error) *MockScheduleStorage_GetScheduleByRoomID_Call {
	_c.Call.Return(schedule, err)
	return _c
}

func (_c *MockScheduleStorage_GetScheduleByRoomID_Call) RunAndReturn(run func(ctx context.Context, roomID string) (*schedules.Schedule, error)) *MockScheduleStorage_GetScheduleByRoomID_Call {
	_c.Call.Return(run)
	return _c
}

// IsScheduleExistsByRoomID provides a mock function for the type MockScheduleStorage
func (_mock *MockScheduleStorage) IsScheduleExistsByRoomID(ctx context.Context, roomID string) (bool, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for IsScheduleExistsByRoomID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduleStorage_IsScheduleExistsByRoomID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsScheduleExistsByRoomID'
type MockScheduleStorage_IsScheduleExistsByRoomID_Call struct {
	*mock.Call
}

// IsScheduleExistsByRoomID is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockScheduleStorage_Expecter) IsScheduleExistsByRoomID(ctx interface{}, roomID interface{}) *MockScheduleStorage_IsScheduleExistsByRoomID_Call {
	return &MockScheduleStorage_IsScheduleExistsByRoomID_Call{Call: _e.mock.On("IsScheduleExistsByRoomID", ctx, roomID)}
}

func (_c *MockScheduleStorage_IsScheduleExistsByRoomID_Call) Run(run func(ctx context.Context, roomID string)) *MockScheduleStorage_IsScheduleExistsByRoomID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScheduleStorage_IsScheduleExistsByRoomID_Call) Return(b bool, err error) *MockScheduleStorage_IsScheduleExistsByRoomID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockScheduleStorage_IsScheduleExistsByRoomID_Call) RunAndReturn(run func(ctx context.Context, roomID string) (bool, error)) *MockScheduleStorage_IsScheduleExistsByRoomID_Call {
	_c.Call.Return(run)
	return _c
}
