// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateRoomUsecase creates a new instance of MockCreateRoomUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateRoomUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateRoomUsecase {
	mock := &MockCreateRoomUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateRoomUsecase is an autogenerated mock type for the CreateRoomUsecase type
type MockCreateRoomUsecase struct {
	mock.Mock
}

type MockCreateRoomUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateRoomUsecase) EXPECT() *MockCreateRoomUsecase_Expecter {
	return &MockCreateRoomUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCreateRoomUsecase
func (_mock *MockCreateRoomUsecase) Execute(ctx context.Context, name string, description string, capacity int) (string, error) {
	ret := _mock.Called(ctx, name, description, capacity)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) (string, error)); ok {
		return returnFunc(ctx, name, description, capacity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) string); ok {
		r0 = returnFunc(ctx, name, description, capacity)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = returnFunc(ctx, name, description, capacity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateRoomUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateRoomUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description string
//   - capacity int
func (_e *MockCreateRoomUsecase_Expecter) Execute(ctx interface{}, name interface{}, description interface{}, capacity interface{}) *MockCreateRoomUsecase_Execute_Call {
	return &MockCreateRoomUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, name, description, capacity)}
}

func (_c *MockCreateRoomUsecase_Execute_Call) Run(run func(ctx context.Context, name string, description string, capacity int)) *MockCreateRoomUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCreateRoomUsecase_Execute_Call) Return(s string, err error) *MockCreateRoomUsecase_Execute_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCreateRoomUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, name string, description string, capacity int) (string, error)) *MockCreateRoomUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
