// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/schedules"
	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/schedules/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateScheduleUsecase creates a new instance of MockCreateScheduleUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateScheduleUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateScheduleUsecase {
	mock := &MockCreateScheduleUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateScheduleUsecase is an autogenerated mock type for the CreateScheduleUsecase type
type MockCreateScheduleUsecase struct {
	mock.Mock
}

type MockCreateScheduleUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateScheduleUsecase) EXPECT() *MockCreateScheduleUsecase_Expecter {
	return &MockCreateScheduleUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCreateScheduleUsecase
func (_mock *MockCreateScheduleUsecase) Execute(ctx context.Context, input dto.CreateScheduleInput) (*schedules.Schedule, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *schedules.Schedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateScheduleInput) (*schedules.Schedule, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateScheduleInput) *schedules.Schedule); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schedules.Schedule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CreateScheduleInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateScheduleUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateScheduleUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.CreateScheduleInput
func (_e *MockCreateScheduleUsecase_Expecter) Execute(ctx interface{}, input interface{}) *MockCreateScheduleUsecase_Execute_Call {
	return &MockCreateScheduleUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockCreateScheduleUsecase_Execute_Call) Run(run func(ctx context.Context, input dto.CreateScheduleInput)) *MockCreateScheduleUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CreateScheduleInput
		if args[1] != nil {
			arg1 = args[1].(dto.CreateScheduleInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateScheduleUsecase_Execute_Call) Return(schedule *schedules.Schedule, err error) *MockCreateScheduleUsecase_Execute_Call {
	_c.Call.Return(schedule, err)
	return _c
}

func (_c *MockCreateScheduleUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, input dto.CreateScheduleInput) (*schedules.Schedule, error)) *MockCreateScheduleUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
