// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/bookings"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingStorage creates a new instance of MockBookingStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingStorage {
	mock := &MockBookingStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingStorage is an autogenerated mock type for the BookingStorage type
type MockBookingStorage struct {
	mock.Mock
}

type MockBookingStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingStorage) EXPECT() *MockBookingStorage_Expecter {
	return &MockBookingStorage_Expecter{mock: &_m.Mock}
}

// CreateBooking provides a mock function for the type MockBookingStorage
func (_mock *MockBookingStorage) CreateBooking(ctx context.Context, slotID string, userID string, conferenceLink *string) (*bookings.Booking, error) {
	ret := _mock.Called(ctx, slotID, userID, conferenceLink)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 *bookings.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string) (*bookings.Booking, error)); ok {
		return returnFunc(ctx, slotID, userID, conferenceLink)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string) *bookings.Booking); ok {
		r0 = returnFunc(ctx, slotID, userID, conferenceLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookings.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *string) error); ok {
		r1 = returnFunc(ctx, slotID, userID, conferenceLink)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingStorage_CreateBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBooking'
type MockBookingStorage_CreateBooking_Call struct {
	*mock.Call
}

// CreateBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - slotID string
//   - userID string
//   - conferenceLink *string
func (_e *MockBookingStorage_Expecter) CreateBooking(ctx interface{}, slotID interface{}, userID interface{}, conferenceLink interface{}) *MockBookingStorage_CreateBooking_Call {
	return &MockBookingStorage_CreateBooking_Call{Call: _e.mock.On("CreateBooking", ctx, slotID, userID, conferenceLink)}
}

func (_c *MockBookingStorage_CreateBooking_Call) Run(run func(ctx context.Context, slotID string, userID string, conferenceLink *string)) *MockBookingStorage_CreateBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookingStorage_CreateBooking_Call) Return(booking *bookings.Booking, err error) *MockBookingStorage_CreateBooking_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingStorage_CreateBooking_Call) RunAndReturn(run func(ctx context.Context, slotID string, userID string, conferenceLink *string) (*bookings.Booking, error)) *MockBookingStorage_CreateBooking_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingByID provides a mock function for the type MockBookingStorage
func (_mock *MockBookingStorage) GetBookingByID(ctx context.Context, bookingID string) (*bookings.Booking, error) {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByID")
	}

	var r0 *bookings.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*bookings.Booking, error)); ok {
		return returnFunc(ctx, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *bookings.Booking); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookings.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingStorage_GetBookingByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingByID'
type MockBookingStorage_GetBookingByID_Call struct {
	*mock.Call
}

// GetBookingByID is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
func (_e *MockBookingStorage_Expecter) GetBookingByID(ctx interface{}, bookingID interface{}) *MockBookingStorage_GetBookingByID_Call {
	return &MockBookingStorage_GetBookingByID_Call{Call: _e.mock.On("GetBookingByID", ctx, bookingID)}
}

func (_c *MockBookingStorage_GetBookingByID_Call) Run(run func(ctx context.Context, bookingID string)) *MockBookingStorage_GetBookingByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingStorage_GetBookingByID_Call) Return(booking *bookings.Booking, err error) *MockBookingStorage_GetBookingByID_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingStorage_GetBookingByID_Call) RunAndReturn(run func(ctx context.Context, bookingID string) (*bookings.Booking, error)) *MockBookingStorage_GetBookingByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsByUserID provides a mock function for the type MockBookingStorage
func (_mock *MockBookingStorage) GetBookingsByUserID(ctx context.Context, userID string) ([]*bookings.Booking, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsByUserID")
	}

	var r0 []*bookings.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*bookings.Booking, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*bookings.Booking); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*bookings.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingStorage_GetBookingsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsByUserID'
type MockBookingStorage_GetBookingsByUserID_Call struct {
	*mock.Call
}

// GetBookingsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBookingStorage_Expecter) GetBookingsByUserID(ctx interface{}, userID interface{}) *MockBookingStorage_GetBookingsByUserID_Call {
	return &MockBookingStorage_GetBookingsByUserID_Call{Call: _e.mock.On("GetBookingsByUserID", ctx, userID)}
}

func (_c *MockBookingStorage_GetBookingsByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockBookingStorage_GetBookingsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingStorage_GetBookingsByUserID_Call) Return(bookings1 []*bookings.Booking, err error) *MockBookingStorage_GetBookingsByUserID_Call {
	_c.Call.Return(bookings1, err)
	return _c
}

func (_c *MockBookingStorage_GetBookingsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*bookings.Booking, error)) *MockBookingStorage_GetBookingsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsPaginated provides a mock function for the type MockBookingStorage
func (_mock *MockBookingStorage) GetBookingsPaginated(ctx context.Context, limit int, offset int) ([]*bookings.Booking, int, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsPaginated")
	}

	var r0 []*bookings.Booking
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*bookings.Booking, int, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*bookings.Booking); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*bookings.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = returnFunc(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBookingStorage_GetBookingsPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsPaginated'
type MockBookingStorage_GetBookingsPaginated_Call struct {
	*mock.Call
}

// GetBookingsPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockBookingStorage_Expecter) GetBookingsPaginated(ctx interface{}, limit interface{}, offset interface{}) *MockBookingStorage_GetBookingsPaginated_Call {
	return &MockBookingStorage_GetBookingsPaginated_Call{Call: _e.mock.On("GetBookingsPaginated", ctx, limit, offset)}
}

func (_c *MockBookingStorage_GetBookingsPaginated_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockBookingStorage_GetBookingsPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingStorage_GetBookingsPaginated_Call) Return(bookings1 []*bookings.Booking, n int, err error) *MockBookingStorage_GetBookingsPaginated_Call {
	_c.Call.Return(bookings1, n, err)
	return _c
}

func (_c *MockBookingStorage_GetBookingsPaginated_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*bookings.Booking, int, error)) *MockBookingStorage_GetBookingsPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBookingStatus provides a mock function for the type MockBookingStorage
func (_mock *MockBookingStorage) UpdateBookingStatus(ctx context.Context, bookingID string, status string) error {
	ret := _mock.Called(ctx, bookingID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookingStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, bookingID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingStorage_UpdateBookingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBookingStatus'
type MockBookingStorage_UpdateBookingStatus_Call struct {
	*mock.Call
}

// UpdateBookingStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
//   - status string
func (_e *MockBookingStorage_Expecter) UpdateBookingStatus(ctx interface{}, bookingID interface{}, status interface{}) *MockBookingStorage_UpdateBookingStatus_Call {
	return &MockBookingStorage_UpdateBookingStatus_Call{Call: _e.mock.On("UpdateBookingStatus", ctx, bookingID, status)}
}

func (_c *MockBookingStorage_UpdateBookingStatus_Call) Run(run func(ctx context.Context, bookingID string, status string)) *MockBookingStorage_UpdateBookingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingStorage_UpdateBookingStatus_Call) Return(err error) *MockBookingStorage_UpdateBookingStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingStorage_UpdateBookingStatus_Call) RunAndReturn(run func(ctx context.Context, bookingID string, status string) error) *MockBookingStorage_UpdateBookingStatus_Call {
	_c.Call.Return(run)
	return _c
}
