// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/schedules"
	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/slots"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSlotStorage creates a new instance of MockSlotStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotStorage {
	mock := &MockSlotStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlotStorage is an autogenerated mock type for the SlotStorage type
type MockSlotStorage struct {
	mock.Mock
}

type MockSlotStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotStorage) EXPECT() *MockSlotStorage_Expecter {
	return &MockSlotStorage_Expecter{mock: &_m.Mock}
}

// CreateSlot provides a mock function for the type MockSlotStorage
func (_mock *MockSlotStorage) CreateSlot(ctx context.Context, roomID string, startTime time.Time, endTime time.Time) (*slots.Slot, error) {
	ret := _mock.Called(ctx, roomID, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for CreateSlot")
	}

	var r0 *slots.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) (*slots.Slot, error)); ok {
		return returnFunc(ctx, roomID, startTime, endTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) *slots.Slot); ok {
		r0 = returnFunc(ctx, roomID, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slots.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, roomID, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotStorage_CreateSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSlot'
type MockSlotStorage_CreateSlot_Call struct {
	*mock.Call
}

// CreateSlot is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - startTime time.Time
//   - endTime time.Time
func (_e *MockSlotStorage_Expecter) CreateSlot(ctx interface{}, roomID interface{}, startTime interface{}, endTime interface{}) *MockSlotStorage_CreateSlot_Call {
	return &MockSlotStorage_CreateSlot_Call{Call: _e.mock.On("CreateSlot", ctx, roomID, startTime, endTime)}
}

func (_c *MockSlotStorage_CreateSlot_Call) Run(run func(ctx context.Context, roomID string, startTime time.Time, endTime time.Time)) *MockSlotStorage_CreateSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSlotStorage_CreateSlot_Call) Return(slot *slots.Slot, err error) *MockSlotStorage_CreateSlot_Call {
	_c.Call.Return(slot, err)
	return _c
}

func (_c *MockSlotStorage_CreateSlot_Call) RunAndReturn(run func(ctx context.Context, roomID string, startTime time.Time, endTime time.Time) (*slots.Slot, error)) *MockSlotStorage_CreateSlot_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSlotsForSchedule provides a mock function for the type MockSlotStorage
func (_mock *MockSlotStorage) CreateSlotsForSchedule(ctx context.Context, roomID string, sched *schedules.Schedule, startDate time.Time) ([]*slots.Slot, error) {
	ret := _mock.Called(ctx, roomID, sched, startDate)

	if len(ret) == 0 {
		panic("no return value specified for CreateSlotsForSchedule")
	}

	var r0 []*slots.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *schedules.Schedule, time.Time) ([]*slots.Slot, error)); ok {
		return returnFunc(ctx, roomID, sched, startDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *schedules.Schedule, time.Time) []*slots.Slot); ok {
		r0 = returnFunc(ctx, roomID, sched, startDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*slots.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *schedules.Schedule, time.Time) error); ok {
		r1 = returnFunc(ctx, roomID, sched, startDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotStorage_CreateSlotsForSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSlotsForSchedule'
type MockSlotStorage_CreateSlotsForSchedule_Call struct {
	*mock.Call
}

// CreateSlotsForSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - sched *schedules.Schedule
//   - startDate time.Time
func (_e *MockSlotStorage_Expecter) CreateSlotsForSchedule(ctx interface{}, roomID interface{}, sched interface{}, startDate interface{}) *MockSlotStorage_CreateSlotsForSchedule_Call {
	return &MockSlotStorage_CreateSlotsForSchedule_Call{Call: _e.mock.On("CreateSlotsForSchedule", ctx, roomID, sched, startDate)}
}

func (_c *MockSlotStorage_CreateSlotsForSchedule_Call) Run(run func(ctx context.Context, roomID string, sched *schedules.Schedule, startDate time.Time)) *MockSlotStorage_CreateSlotsForSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *schedules.Schedule
		if args[2] != nil {
			arg2 = args[2].(*schedules.Schedule)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSlotStorage_CreateSlotsForSchedule_Call) Return(slots1 []*slots.Slot, err error) *MockSlotStorage_CreateSlotsForSchedule_Call {
	_c.Call.Return(slots1, err)
	return _c
}

func (_c *MockSlotStorage_CreateSlotsForSchedule_Call) RunAndReturn(run func(ctx context.Context, roomID string, sched *schedules.Schedule, startDate time.Time) ([]*slots.Slot, error)) *MockSlotStorage_CreateSlotsForSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// GetFreeSlots provides a mock function for the type MockSlotStorage
func (_mock *MockSlotStorage) GetFreeSlots(ctx context.Context, roomID string, dayStart time.Time, dayEnd time.Time) ([]*slots.Slot, error) {
	ret := _mock.Called(ctx, roomID, dayStart, dayEnd)

	if len(ret) == 0 {
		panic("no return value specified for GetFreeSlots")
	}

	var r0 []*slots.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*slots.Slot, error)); ok {
		return returnFunc(ctx, roomID, dayStart, dayEnd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*slots.Slot); ok {
		r0 = returnFunc(ctx, roomID, dayStart, dayEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*slots.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, roomID, dayStart, dayEnd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotStorage_GetFreeSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFreeSlots'
type MockSlotStorage_GetFreeSlots_Call struct {
	*mock.Call
}

// GetFreeSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - dayStart time.Time
//   - dayEnd time.Time
func (_e *MockSlotStorage_Expecter) GetFreeSlots(ctx interface{}, roomID interface{}, dayStart interface{}, dayEnd interface{}) *MockSlotStorage_GetFreeSlots_Call {
	return &MockSlotStorage_GetFreeSlots_Call{Call: _e.mock.On("GetFreeSlots", ctx, roomID, dayStart, dayEnd)}
}

func (_c *MockSlotStorage_GetFreeSlots_Call) Run(run func(ctx context.Context, roomID string, dayStart time.Time, dayEnd time.Time)) *MockSlotStorage_GetFreeSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSlotStorage_GetFreeSlots_Call) Return(slots1 []*slots.Slot, err error) *MockSlotStorage_GetFreeSlots_Call {
	_c.Call.Return(slots1, err)
	return _c
}

func (_c *MockSlotStorage_GetFreeSlots_Call) RunAndReturn(run func(ctx context.Context, roomID string, dayStart time.Time, dayEnd time.Time) ([]*slots.Slot, error)) *MockSlotStorage_GetFreeSlots_Call {
	_c.Call.Return(run)
	return _c
}

// GetSlotByID provides a mock function for the type MockSlotStorage
func (_mock *MockSlotStorage) GetSlotByID(ctx context.Context, slotID string) (*slots.Slot, error) {
	ret := _mock.Called(ctx, slotID)

	if len(ret) == 0 {
		panic("no return value specified for GetSlotByID")
	}

	var r0 *slots.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*slots.Slot, error)); ok {
		return returnFunc(ctx, slotID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *slots.Slot); ok {
		r0 = returnFunc(ctx, slotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slots.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slotID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotStorage_GetSlotByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlotByID'
type MockSlotStorage_GetSlotByID_Call struct {
	*mock.Call
}

// GetSlotByID is a helper method to define mock.On call
//   - ctx context.Context
//   - slotID string
func (_e *MockSlotStorage_Expecter) GetSlotByID(ctx interface{}, slotID interface{}) *MockSlotStorage_GetSlotByID_Call {
	return &MockSlotStorage_GetSlotByID_Call{Call: _e.mock.On("GetSlotByID", ctx, slotID)}
}

func (_c *MockSlotStorage_GetSlotByID_Call) Run(run func(ctx context.Context, slotID string)) *MockSlotStorage_GetSlotByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSlotStorage_GetSlotByID_Call) Return(slot *slots.Slot, err error) *MockSlotStorage_GetSlotByID_Call {
	_c.Call.Return(slot, err)
	return _c
}

func (_c *MockSlotStorage_GetSlotByID_Call) RunAndReturn(run func(ctx context.Context, slotID string) (*slots.Slot, error)) *MockSlotStorage_GetSlotByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSlotsByDate provides a mock function for the type MockSlotStorage
func (_mock *MockSlotStorage) GetSlotsByDate(ctx context.Context, roomID string, dayStart time.Time, dayEnd time.Time) ([]*slots.Slot, error) {
	ret := _mock.Called(ctx, roomID, dayStart, dayEnd)

	if len(ret) == 0 {
		panic("no return value specified for GetSlotsByDate")
	}

	var r0 []*slots.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*slots.Slot, error)); ok {
		return returnFunc(ctx, roomID, dayStart, dayEnd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*slots.Slot); ok {
		r0 = returnFunc(ctx, roomID, dayStart, dayEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*slots.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, roomID, dayStart, dayEnd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotStorage_GetSlotsByDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlotsByDate'
type MockSlotStorage_GetSlotsByDate_Call struct {
	*mock.Call
}

// GetSlotsByDate is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - dayStart time.Time
//   - dayEnd time.Time
func (_e *MockSlotStorage_Expecter) GetSlotsByDate(ctx interface{}, roomID interface{}, dayStart interface{}, dayEnd interface{}) *MockSlotStorage_GetSlotsByDate_Call {
	return &MockSlotStorage_GetSlotsByDate_Call{Call: _e.mock.On("GetSlotsByDate", ctx, roomID, dayStart, dayEnd)}
}

func (_c *MockSlotStorage_GetSlotsByDate_Call) Run(run func(ctx context.Context, roomID string, dayStart time.Time, dayEnd time.Time)) *MockSlotStorage_GetSlotsByDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSlotStorage_GetSlotsByDate_Call) Return(slots1 []*slots.Slot, err error) *MockSlotStorage_GetSlotsByDate_Call {
	_c.Call.Return(slots1, err)
	return _c
}

func (_c *MockSlotStorage_GetSlotsByDate_Call) RunAndReturn(run func(ctx context.Context, roomID string, dayStart time.Time, dayEnd time.Time) ([]*slots.Slot, error)) *MockSlotStorage_GetSlotsByDate_Call {
	_c.Call.Return(run)
	return _c
}
