// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/bookings"
	"github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/bookings/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateBookingUsecase creates a new instance of MockCreateBookingUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateBookingUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateBookingUsecase {
	mock := &MockCreateBookingUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateBookingUsecase is an autogenerated mock type for the CreateBookingUsecase type
type MockCreateBookingUsecase struct {
	mock.Mock
}

type MockCreateBookingUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateBookingUsecase) EXPECT() *MockCreateBookingUsecase_Expecter {
	return &MockCreateBookingUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCreateBookingUsecase
func (_mock *MockCreateBookingUsecase) Execute(ctx context.Context, input dto.CreateBookingInput) (*bookings.Booking, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *bookings.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateBookingInput) (*bookings.Booking, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateBookingInput) *bookings.Booking); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookings.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CreateBookingInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateBookingUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateBookingUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.CreateBookingInput
func (_e *MockCreateBookingUsecase_Expecter) Execute(ctx interface{}, input interface{}) *MockCreateBookingUsecase_Execute_Call {
	return &MockCreateBookingUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockCreateBookingUsecase_Execute_Call) Run(run func(ctx context.Context, input dto.CreateBookingInput)) *MockCreateBookingUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CreateBookingInput
		if args[1] != nil {
			arg1 = args[1].(dto.CreateBookingInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateBookingUsecase_Execute_Call) Return(booking *bookings.Booking, err error) *MockCreateBookingUsecase_Execute_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockCreateBookingUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, input dto.CreateBookingInput) (*bookings.Booking, error)) *MockCreateBookingUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
