all: false

packages:
  github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/rooms:
    interfaces:
      RoomStorage:
        config:
          dir: internal/mocks
          pkgname: mocks
          filename: mock_{{.InterfaceName | lower}}.go
          structname: Mock{{.InterfaceName}}
          template: testify
  github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/schedules:
    interfaces:
      ScheduleStorage:
        config:
          dir: internal/mocks
          pkgname: mocks
          filename: mock_{{.InterfaceName | lower}}.go
          structname: Mock{{.InterfaceName}}
          template: testify
  github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/slots:
    interfaces:
      SlotStorage:
        config:
          dir: internal/mocks
          pkgname: mocks
          filename: mock_{{.InterfaceName | lower}}.go
          structname: Mock{{.InterfaceName}}
          template: testify
  github.com/avito-internships/test-backend-1-EmotionlessDev/internal/domain/bookings:
    interfaces:
      BookingStorage:
        config:
          dir: internal/mocks
          pkgname: mocks
          filename: mock_{{.InterfaceName | lower}}.go
          structname: Mock{{.InterfaceName}}
          template: testify
